### ISSUE TITLE
Runtime Required For An Image?

### ISSUE THREAD

**Issue by codergg4393** [yaksoy/SemanticSoftSegmentation#1]
This is incredible and exciting to see this grow.

First, I am not sure if I can post questions here. Feel free to close it if it's not the right place. 

I wanted to ask, is the runtime per image same as stated in the paper? That is, 

>  runtime for a 640 × 480 image lies between 3 and 4 minutes

The paper also states this

>  The efficiency of our method can be optimized in several ways, such as multi-scale solvers, but an efficient implementation of linear solvers and eigendecomposition lies beyond the scope of our paper.
 
So my question is, is this code optimized and could require less runtime or it's going to be 3-4 mins per image as stated in the paper?

Let me know,
Thank you!

**Comment by yaksoy** [comment]
This implementation is the same as the one reported in the paper.
