### ISSUE TITLE
How could I transform soft segmentation results to alpha mattes?

### ISSUE THREAD

**Issue by Diligentfight** [yaksoy/SemanticSoftSegmentation#10]
Question like the title。
![image](https://user-images.githubusercontent.com/22612343/50757938-b3f63a00-129b-11e9-8836-f599f924b39f.png)
Like picture in your paper.

**Comment by Diligentfight** [comment]
And another question is if I want just predict one special class could I get better performance.for example, Could I just use one class to train for better performance.

**Comment by jammm** [comment]
I'm wondering the same. My guess is that it could be the largest alpha matte obtained via doOrdering set to true in visualizeSoftSegments which generates a predictable set of colors of each segment.

**Comment by shyyhs** [comment]
I'm considering first use Mask RCNN to recognize the object. Then use results from MaskRCNN and SSS to generate the alpha mattes by selecting the class of objects(for example people and cat) while ignoring other objects.

**Comment by yaksoy** [comment]
Each channel in the soft segmentation result is a matte, combine them by adding several or just use one channel as the matte.

Please refer to the paper on how to replace the features, extend the definition of semantics etc.
