### ISSUE TITLE
Python port?

### ISSUE THREAD

**Issue by sklipnoty** [yaksoy/SemanticSoftSegmentation#11]
Hello 

I would love to try the technique introduced in the paper. However I do not have Matlab and find it honestly a not so great idea to mix both Matlab and Python code. Is is possible to release a python port of this project. (Which seems to be the standard for neural networks.)

Best regards

**Comment by yaksoy** [comment]
Of course it is possible, all the algorithmic details are included in the paper. Feel free to release a Python version.
