### ISSUE TITLE
About   the input data of  demo.m 

### ISSUE THREAD

**Issue by zjz5250** [yaksoy/SemanticSoftSegmentation#14]
I found the image and  features used in demo.m as follows:
image = imread('docia.png');
features = image(:, size(image, 2) / 2 + 1 : end, :);
  and  It can show the segmentation result。
but  I have a question，what is the relation  between this project and the sister project ，the  python realization version http://people.inf.ethz.ch/aksoyy/sss/？
 another question：
   when I input the 128 dimension features，the segmentation result is similar with the above。
so  why do you  need  the sister  implementation？  we can get the  soft semantic segmentation result just using this project，can we？
many thanks！

**Comment by yaksoy** [comment]
Just read the description and the paper. You need both.
