### ISSUE TITLE
when i run demo.m for test ,i have qustion 

### ISSUE THREAD

**Issue by andrewwyl** [yaksoy/SemanticSoftSegmentation#15]
No function or variable is defined  'adjacentRegionsGraph'。

**Comment by Lakshaysharma048** [comment]
Hi all,

i am also getting stuck here only. Can you please help.

**Comment by zacario-li** [comment]
> No function or variable is defined 'adjacentRegionsGraph'。
https://ww2.mathworks.cn/matlabcentral/fileexchange/53614-image-graphs

**Comment by zacario-li** [comment]
> Hi all,
> 
> i am also getting stuck here only. Can you please help.
https://ww2.mathworks.cn/matlabcentral/fileexchange/53614-image-graphs

**Comment by yaksoy** [comment]
Just read the description.
