### ISSUE TITLE
Not able to integrate in Octave

### ISSUE THREAD

**Issue by makaveli10** [yaksoy/SemanticSoftSegmentation#16]
Image graphs exist in matgeom package of octave but not able to find it here. Please let me know if this repo can be run in octave

>> demo
warning: addpath: /home/saurabh/Documents/code/SemanticSoftSegmentation/ImageGraph: No such file or directory
warning: called from
    demo at line 4 column 1
Semantic Soft Segmentation
error: 'superpixels' undefined near line 18 column 20
error: called from
    Superpixels at line 18 column 18
    SemanticSoftSegmentation at line 17 column 17
    demo at line 20 column 5

**Comment by yaksoy** [comment]
Never tested on Octave. Image graphs is external, linked in the description.
