### ISSUE TITLE
Remove Background

### ISSUE THREAD

**Issue by makaveli10** [yaksoy/SemanticSoftSegmentation#18]
Since, this is the first time I am using matlab and very curious to reproduce every result from the paper; Can you help to remove background. How to proceed in removing background after soft segmentation?
![fig](https://user-images.githubusercontent.com/39617050/75790303-01334600-5d91-11ea-967a-3ee02a9e315c.png)

This file is generated after running demo.m. Now i want to remove whatever is there in the background. Please give me a direction to follow?

**Comment by yaksoy** [comment]
You should read the paper.
