### ISSUE TITLE
it's an error in Superpixels.m file

### ISSUE THREAD

**Issue by shijh1975** [yaksoy/SemanticSoftSegmentation#2]
@yaksoy , In this file,   the  code ：[L, N] = superpixels(im, spcnt, 'Compactness', 1e-20); it seem no superpixels function in this file. Can you help me?

**Comment by shijh1975** [comment]
My matlab version is too low. Thank you.

**Comment by Diligentfight** [comment]
Hi，which version could be ok?

**Comment by shijh1975** [comment]
I use matlab2016，it seem ok！

**Comment by CS-savvy** [comment]
can you tell me how you solved this error.?

**Comment by CS-savvy** [comment]
superpixels function present in the latest Matlab image processing toolbox.
