### ISSUE TITLE
there are somes errors,can you help me~

### ISSUE THREAD

**Issue by zhouyuan888888** [yaksoy/SemanticSoftSegmentation#3]
when I running  this code ,there are some errors:
错误使用  .* 
矩阵维度必须一致。

出错 groupSegments (line 12)
        cc = segments(:,:,i) .* features;

出错 SemanticSoftSegmentation (line 42)
    groupedSegments = groupSegments(initSoftSegments, features);

出错 demo (line 20)
sss = SemanticSoftSegmentation(image, features);

I don't know what the thing I mistake, can you help me to solve this problem.

thankyou !

**Comment by owang** [comment]
I had the same problem, I had to replicate the segments to match the number of channels of the features:

Change
```
cc = segments(:,:,i) .* features;
```

To 
```
cc = bsxfun(@times,segments(:,:,i),features);
```

I'm not sure if this is right? But it seemed to work.

**Comment by zhouyuan888888** [comment]
@owang thank you ,I already use this approch the same as yours to slove this problem sometimes ago ,

**Comment by lph529372693** [comment]
> @owang thank you ,I already use this approch the same as yours to slove this problem sometimes ago ,

Have you solved this problem?How to do
