### ISSUE TITLE
Getting different results!!!!

### ISSUE THREAD

**Issue by zq649** [yaksoy/SemanticSoftSegmentation#4]
Hi,
I used your semantic feature generation code to generate the features of the images 'docia.png'. But I am facing difference in the results. Please see the images below and guide me if I am doing anything wrong. You can see the difference in the features generated. After getting the feature vector I am feeding that vector to 'preprocessFeatures.m' file. Is there something else that I need to do?

In this picture I generated the feature through the code and then fed the image as input in demo.m file.
![outsamp](https://user-images.githubusercontent.com/37440553/45267857-a8ca0380-b48d-11e8-982c-c3cba3d9286e.png) 
This result is generated by the image you provided as docia.png
![untitled1](https://user-images.githubusercontent.com/37440553/45267861-b4b5c580-b48d-11e8-9bf9-ae932b729a6a.png)

**Comment by yaksoy** [comment]
Hey,

No that's all you needed to do. I don't know why the network is generating these different results, somehow it is unable to differentiate between the hills in BG and the person, which is unusual. I'll try to look into it in the following weeks.

**Comment by zq649** [comment]
Hi did you check the problem?

**Comment by Senyao-Han** [comment]
I had the same problem. I got this too.
![result_me](https://user-images.githubusercontent.com/25421473/46902155-d40f9a80-cef2-11e8-810a-a3d8311f8997.png)

**Comment by xwasco** [comment]
Hi @qasimz  @Senyao-Han @yaksoy , got the same results at the beginning (with the person wrongly segmented). 

If you resize the image to (320x320), then perform feature extraction with the net (python) and then do the soft segmentation (matlab) the result is the following:
![image](https://user-images.githubusercontent.com/5593715/47156145-c12c0a00-d2e6-11e8-8706-3c169fd34b4f.png)

... which is quite close to the one produced by the docia.png

Enjoy

PS: congratz for this work!

**Comment by betterway-tinyman** [comment]
![image](https://user-images.githubusercontent.com/13364649/49427804-a73b7d80-f7e7-11e8-9a1f-7da72e9afc41.png)

@xwasco 
I also found the same problem as the picture above. I want to know if I have developed the source code again with Python. How did you solve this? If you have a new implementation, I want to know if you can share it.

**Comment by yaksoy** [comment]
This is not an issue, there is some randomness especially while combining the soft segments into 5. You may get slightly different results, but you can also combine several layers to give you a matte for a specific object by adding two soft segments. Please refer to the paper for details.
