### ISSUE TITLE
preprocessFeatures.m PCA dimensionality  reduction problem

### ISSUE THREAD

**Issue by BTUJACK** [yaksoy/SemanticSoftSegmentation#5]
### **in MATLAB command line:**
>>features = load('docia.mat');  %docia.mat is the 128 dimensionality features
>>image= imread('docia_one.png'); %docia_one.png is the origianl picture
>> preprocessFeatures(features, image)

The operator '<' that corresponds to the input parameter of type 'struct' is not defined.

wrong preprocessFeatures (line 7)
    features(features < -5) = -5;

### **my analysis:**
features is a 640*640*128 array, but -5 is just a number. 
They can not be compared.

**### my aim:**
I want to use the file preprocessFeatures.m to reduce the dimensionality of hyper-dimensional semantic feature vectors as described in Section 3.5 which is generated by the Python program.

**Comment by quxiaofeng** [comment]
When `load()` by matlab, the 128-dim feature is a field (`embedmap`) of a structure. It needs to be unpacked.

```
tmp = load('docia.mat');
features = tmp.embedmap;
```

**Comment by BTUJACK** [comment]
> When `load()` by matlab, the 128-dim feature is a field (`embedmap`) of a structure. It needs to be unpacked.
> 
> ```
> tmp = load('docia.mat');
> features = tmp.embedmap;
> ```

thanks your reply. I fixed it. 
Thx
