### ISSUE TITLE
Everytime I run the code with same image, I get a different result. Why?

### ISSUE THREAD

**Issue by Senyao-Han** [yaksoy/SemanticSoftSegmentation#8]
![new4_result](https://user-images.githubusercontent.com/25421473/46936110-dce9a300-d08f-11e8-9387-8a127eb0fb5c.png)
![new4_result2](https://user-images.githubusercontent.com/25421473/46936113-deb36680-d08f-11e8-93d0-741d44d1e67c.png)
![new4_result3](https://user-images.githubusercontent.com/25421473/46936114-dfe49380-d08f-11e8-80c2-71d776fc8b06.png)

**Comment by whcjb** [comment]
i have meet the same problem, what's the reason?
![image](https://user-images.githubusercontent.com/11767995/114389663-dd634600-9bc7-11eb-9414-d9d5851f921b.png)
![image](https://user-images.githubusercontent.com/11767995/114389692-e6ecae00-9bc7-11eb-9912-8ab2f7d361a8.png)
