### ISSUE TITLE
How to transform mat into PNG?

### ISSUE THREAD

**Issue by mengxiabing** [yaksoy/SemanticSoftSegmentation#9]
How to transform mat into PNG? How to reduce dimensions?

**Comment by samuel-cox** [comment]
@mengxiabing did you work this step out?

**Comment by guojting** [comment]
I have got the same problem. Did you work it out?

**Comment by samuel-cox** [comment]
> I have got the same problem. Did you work it out?

No, I haven't had too much time to play around with this since I asked the question. Please let me know if you do figure it out though.

**Comment by DustinJSilk** [comment]
Anyone have an update on this?

Trying to do the same thing. Not exactly sure what the 128-dimension array is.
When I slice the array to [:, :, 3] and view it as a png it's wildly colourful and looks like its showing some kind of incomplete edge data

**Comment by yaksoy** [comment]
Each channel in the soft segmentation result is another matte. Combine them if you wish by adding multiple, or select a single channel to use as the matte.

Please refer to the paper for the semantic features, to understand the contents of 'the 128-dimension array'.

**Comment by ghost** [comment]
@samuel-cox @DustinJSilk @guojting  in case you haven't figured it out. After reshaping the mat['embedmap'] from (height, width, dimensions) to (height*width, dimensions) . Just use PCA to lower the dimension to 3 and then perform min-max normalization.
